version: "3.8"

services:
    nginx:
        image: nginx:1.20.0
        ports:
            - 8080:8080
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./app:/var/www/html
        networks:
            - net-prestashop

    app:
        build: ./app
        volumes:
            - ./app:/var/www/html
        networks:
            - net-prestashop

    mariadb:
        image: mariadb:10.6.0
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: prestashop
        volumes:
            - ./mariadb:/var/lib/mysql 
        networks:
            - net-prestashop

    phpmyadmin:
        image: phpmyadmin:5.1.0
        ports:
            - 8081:80
        environment:
            PMA_HOST: mariadb
            PMA_PORT: 3306
        networks:
            - net-prestashop

networks: 
    net-prestashop:
        external: true